name: pdf_renderer
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  advance_pdf_viewer: ^1.1.6
  indexed_list_view: ^1.0.9
  photo_view: ^0.9.2
  cupertino_icons: ^0.1.3
  flutter_advanced_networkimage: ^0.7.0
  flutter_pdfview: ^1.0.2+4
  path_provider: ^1.6.10
  equatable: ^1.2.0
  async: ^2.4.1
  flutter_bloc: ^5.0.0
  http: ^0.12.1
  printing: ^3.5.0
  image: ^2.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/text.pdf
